[platformio]
extra_configs =
  platformio.local.ini

[env]
platform = espressif8266
framework = arduino
board_build.f_cpu = 160000000L
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder, default
board_build.filesystem = littlefs

;lib_ldf_mode = deep+
; для fastled из github пока что убрал изза долгой загрузки, после публикации в registry вернуть
lib_ldf_mode = chain
lib_compat_mode = strict

lib_deps =
  https://github.com/FastLED/FastLED#2fe8316eeec338af1d6caecfe95a12f0610e37d1 ;fastled/FastLED@3.10.4
  GyverLibs/Settings@1.3.17
  paulino/HaMqttEntities@1.0.12
  gyverlibs/EncButton@3.7.5
  hmueller01/pubsubclient3@3.3.0
  yiannisbourkelis/Uptime Library@1.0.0
  esphome/ESPAsyncWebServer-esphome
  esphome/ESPAsyncTCP-esphome
build_flags =
  -D FIRMWARE_VERSION=\"1.0.0\"
build_src_flags =
;  -D FASTLED_INTERRUPT_RETRY_COUNT=0 ; FastLED - без этого хорошо работает
;  -D FASTLED_ALLOW_INTERRUPTS=0      ; FastLED - баз этого хорошо работает
  -D FASTLED_ESP8266_RAW_PIN_ORDER    ; FastLED
  -D FASTLED_ESP8266_UART             ; FastLED - включение управления UART, чуть больше занимаемого RAM, меньше фризов
  -D HA_MAX_PAYLOAD_LENGTH=1536       ; HaMqttEntities - из-за большого списка эффектов нужно увеличить буфер
  -D SETT_NO_DB                       ; Settings
  -D SETT_NO_TABLE                    ; Settings
