[platformio]
extra_configs =
  platformio.local.ini

[env]
framework = arduino
board_build.filesystem = littlefs
extra_scripts = pre:extra_script.py
build_unflags =
  -std=gnu++11

check_tool = clangtidy
check_flags =
  clangtidy: --config-file=.clang-tidy

;lib_ldf_mode = deep+
; для fastled из github пока что убрал изза долгой загрузки, после публикации в registry вернуть
lib_ldf_mode = chain
lib_compat_mode = strict

lib_deps =
  https://github.com/FastLED/FastLED#ba8cef0d0cd6bbe47358b9281d8c6e89adc38ff9 ;fastled/FastLED@3.10.4
  GyverLibs/Settings@1.4.3
  gyverlibs/EncButton@3.7.6
  hmueller01/pubsubclient3@3.3.0
  yiannisbourkelis/Uptime Library@1.0.0
build_src_flags =
  -D FIRMWARE_VERSION=\"1.5.0\"
;  -D FASTLED_INTERRUPT_RETRY_COUNT=0 ; FastLED - без этого хорошо работает
;  -D FASTLED_ALLOW_INTERRUPTS=0      ; FastLED - баз этого хорошо работает
  -D SETT_NO_DB                       ; Settings
  -D SETT_NO_TABLE                    ; Settings

[target_d1_mini]
platform = espressif8266@4.2.1
board = d1_mini
board_build.f_cpu = 160000000L
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder, default
lib_deps =
  ${env.lib_deps}
  esphome/ESPAsyncWebServer-esphome@3.4.0
  esphome/ESPAsyncTCP-esphome@2.0.0
build_src_flags =
  ${env.build_src_flags}
  -D FASTLED_ESP8266_RAW_PIN_ORDER    ; FastLED
  -D FASTLED_ESP8266_UART             ; FastLED - включение управления UART, чуть больше занимаемого RAM, меньше фризов

[target_esp32dev]
platform = espressif32@6.5.0
board = esp32dev
board_build.partitions = partitions_esp32dev.csv
upload_speed = 115200
monitor_speed = 115200
monitor_filters = default
lib_deps =
  ${env.lib_deps}
  esphome/ESPAsyncWebServer-esphome@3.4.0
  esphome/AsyncTCP-esphome@2.1.4
build_src_flags =
  ${env.build_src_flags}
