[platformio]
default_envs = diag
extra_configs = platformio.local.ini

[env]
platform = espressif32@6.5.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800

[env:diag]
build_flags =
  -D PANEL_DIAG
build_src_filter =
  +<diag/>
  -<input/>

[env:input]
lib_deps =
  gyverlibs/uEncoder@1.1.0
  gyverlibs/uButton@1.1.3
  gyverlibs/GyverIO@1.4.2
build_flags =
  -D PANEL_INPUT
  -D PANEL_STATUS_LED_PIN=-1
  -D UB_DEB_TIME=30
  -D UB_CLICK_TIME=300
  -D UB_HOLD_TIME=650
build_src_filter =
  +<input/>
  -<diag/>

[env:radio]
lib_deps =
  gyverlibs/uEncoder@1.1.0
  gyverlibs/uButton@1.1.3
  gyverlibs/GyverIO@1.4.2
build_src_filter =
  -<radio/>
  -<diag/>
  -<input/>

[env:profile]
extends = env:radio
build_unflags =
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
  ${env:radio.lib_deps}
lib_extra_dirs =
  ../lib
build_flags =
  -D PANEL_PROVISIONED
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D PANEL_STATUS_LED_PIN=-1
  -D UB_DEB_TIME=30
  -D UB_CLICK_TIME=300
  -D UB_HOLD_TIME=650
extra_scripts = pre:extra_script.py
build_src_filter =
  +<radio/>
  -<diag/>
  -<input/>
